extern const GeoLayout onBlock_Bone_001_opt1[];
extern const GeoLayout onBlock_Bone_001_opt2[];
extern const GeoLayout onBlock_geo[];
extern u8 onBlock_exclamation_box_outline_rgba16_ia8[];
extern Vtx onBlock_Bone_002_mesh_layer_4_vtx_0[24];
extern Gfx onBlock_Bone_002_mesh_layer_4_tri_0[];
extern Gfx mat_onBlock_Off[];
extern Gfx mat_revert_onBlock_Off[];
extern Gfx mat_onBlock_On[];
extern Gfx mat_revert_onBlock_On[];
extern Gfx onBlock_Bone_002_mesh_layer_4[];
extern Gfx onBlock_Bone_002_mesh_layer_4_mat_override_On_0[];
extern Gfx onBlock_Bone_002_mesh_layer_4_mat_override_Off_1[];
